os:
  - linux
#  - osx

language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3" #fails misteriously
  - "3.4"
  - "3.5"
#  - "nightly"
#virtualenv:
#    system_site_packages: NO !!!
# the system python and the one from travis have been compiled with different options

addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libhdf5-serial-1.8.4
      - libhdf5-serial-dev
      - gfortran
      - libatlas-base-dev
      - libqtcore4
#For OpenCL:
      - libboost1.48-dev
      - libboost-python-dev
      - libboost-python1.48
      - fglrx
      - opencl-headers
# command to install dependencies

#before_install:
#  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/before_install-linux.sh; fi"
#  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

install:
  - "python info_platform.py"
  - "pip install --upgrade pip"
  - "pip install cython --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse"
  - "pip install --upgrade numpy --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse"
  - "pip install --upgrade --trusted-host www.edna-site.org -r requirements_travis.txt"
  - "python info_platform.py"
  - "python setup.py build"
  - "python setup.py bdist_wheel"
  - "pip install --pre --no-index --find-links dist/ pyFAI"

# command to run tests
script:
  - "python setup.py test"
  - "python ./run_tests.py"
